version: '3'
services:

  php:
    container_name: krakenditor-php
    image:          php:fpm-alpine3.10
    restart:        always
    volumes:
      - ./app:/var/www/html
    networks:
      - net

  nginx:
    container_name: krakenditor-nginx
    image:          nginx:1.17-alpine
    restart:        always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./app:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=traefik
      - traefik.frontend.rule=Host:krakenditor.local
    networks:
      - traefik
      - net

networks:
  net:
  traefik:
    external: true
